language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_module

node_js: stable

install:
  - yarn
  - cd ./test/smoke/template
  - yarn
  - cd ../../../

scripts:
  - yarn run test
  - yarn run coverage